import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';

const source = readFileSync(new URL('../Utils.js', import.meta.url), 'utf8');

const section = (text, startMarker, endMarker) => {
    const start = text.indexOf(startMarker);
    const end = text.indexOf(endMarker, start + startMarker.length);
    assert.ok(start >= 0 && end > start, `missing source section: ${startMarker}`);
    return text.slice(start, end);
};

// Pure community-list gate: the video background must stay empty when the
// server list is empty instead of falling back to a stale or auto-matched video.
const helperSource = section(
    source,
    'const resolveCommunityVideoSelection = (',
    '\n// === end community video selection ==='
);
const context = vm.createContext({});
vm.runInContext(
    `${helperSource}\nglobalThis.__communityVideoResolutionTest = { resolveCommunityVideoSelection };`,
    context
);
const { resolveCommunityVideoSelection } = context.__communityVideoResolutionTest;

const entry = (overrides = {}) => ({
    id: 1,
    youtubeVideoId: 'ABCDEFGHIJK',
    youtubeTitle: 'Somewhere Again (Official)',
    startTime: 1.5,
    skipSegments: [],
    submitterId: 'user-1',
    isAutoGenerated: false,
    userVote: 0,
    likes: 5,
    dislikes: 0,
    ...overrides,
});

const saved = (overrides = {}) => ({
    youtubeVideoId: 'ABCDEFGHIJK',
    youtubeTitle: 'saved title',
    captionStartTime: 1.5,
    skipSegments: [],
    communityEntryId: 1,
    isAutoGenerated: false,
    ...overrides,
});

test('empty community list resolves to no video', () => {
    const decision = resolveCommunityVideoSelection({ videos: [], savedVideo: null });
    assert.equal(decision.status, 'none');
});

test('empty community list drops a stale saved selection', () => {
    const decision = resolveCommunityVideoSelection({
        videos: [],
        savedVideo: saved({ communityEntryId: 99, youtubeVideoId: 'STALEVemd321' }),
    });
    assert.equal(decision.status, 'none');
    assert.equal(decision.dropSavedVideo, true);
});

test('saved selection still listed keeps playing', () => {
    const decision = resolveCommunityVideoSelection({
        videos: [entry()],
        savedVideo: saved(),
    });
    assert.equal(decision.status, 'play');
    assert.equal(decision.useSavedVideo, true);
});

test('saved selection missing from the list falls back to the top entry', () => {
    const top = entry({ id: 7, youtubeVideoId: 'TOPVIDE0123' });
    const decision = resolveCommunityVideoSelection({
        videos: [top],
        savedVideo: saved({ communityEntryId: 99, youtubeVideoId: 'STALEVemd321' }),
    });
    assert.equal(decision.status, 'play');
    assert.equal(decision.useSavedVideo, false);
    assert.equal(decision.entry.youtubeVideoId, 'TOPVIDE0123');
    assert.equal(decision.dropSavedVideo, true);
});

test('disliked saved selection is replaced when hiding disliked videos', () => {
    const disliked = entry({ id: 1, youtubeVideoId: 'DISLIKEDv123', userVote: -1 });
    const replacement = entry({ id: 2, youtubeVideoId: 'REPLACEme12' });
    const decision = resolveCommunityVideoSelection({
        videos: [disliked, replacement],
        savedVideo: saved({ communityEntryId: 1, youtubeVideoId: 'DISLIKEDv123' }),
        hideDisliked: true,
    });
    assert.equal(decision.status, 'play');
    assert.equal(decision.entry.youtubeVideoId, 'REPLACEme12');
});

test('all entries disliked resolves to no video', () => {
    const decision = resolveCommunityVideoSelection({
        videos: [entry({ userVote: -1 })],
        savedVideo: null,
        hideDisliked: true,
    });
    assert.equal(decision.status, 'none');
});

test('local-only saved video still plays with an empty list', () => {
    const decision = resolveCommunityVideoSelection({
        videos: [],
        savedVideo: saved({ isLocalOnly: true, communityEntryId: null }),
    });
    assert.equal(decision.status, 'play');
    assert.equal(decision.useSavedVideo, true);
});
